[build]
  publish = "dist"
  external_node_modules = ["axios"]
  functions = "functions"
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200


